# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://direitoemdados.com" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Direito em Dados
  avatar: avatar.png
  description: "Blog sobre Direito, Estatística, Matemática, Jurimetria, Previsões, Programação e assuntos relacionados." # used by search engines
  
  # Header and footer text
  header_text: >
     <img src="img/avatar.png" height="80" width="80"> </img> <p>Blog sobre Direito, Estatística, Matemática, Jurimetria, Previsões, Programação e assuntos relacionados.</p>
     
  footer_text: >
   Powered by <a href="http://jekyllrb.com">Jekyll</a> with <a href="https://rohanchandra.github.io/project/type.html">Type Theme</a>
  
  # Icons
  rss: false
  email_address: "gjardimduarte@gmail.com" # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: 
  flickr: 
  github: "github"
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "twitter.com/guilhermejd_"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Próximo"
  str_prev: "Anterior"
  str_continue_reading: "Continue lendo"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
